import * as CSS from 'csstype';

export type CommonAllowedCss = Pick<
  CSS.Properties,
  | 'margin'
  | 'marginTop'
  | 'marginRight'
  | 'marginBottom'
  | 'marginLeft'
  | 'padding'
  | 'paddingTop'
  | 'paddingRight'
  | 'paddingBottom'
  | 'paddingLeft'
  | 'display'
  | 'color'
  | 'background'
  | 'backgroundColor'
  | 'fontFamily'
  | 'fontStyle'
  | 'fontWeight'
  | 'lineHeight'
  | 'width'
  | 'height'
  | 'maxWidth'
  | 'maxHeight'
  | 'border'
  | 'borderWidth'
  | 'borderColor'
  | 'borderStyle'
  | 'borderTop'
  | 'borderTopWidth'
  | 'borderTopColor'
  | 'borderTopStyle'
  | 'borderRight'
  | 'borderRightWidth'
  | 'borderRightColor'
  | 'borderRightStyle'
  | 'borderBottom'
  | 'borderBottomWidth'
  | 'borderBottomColor'
  | 'borderBottomStyle'
  | 'borderLeft'
  | 'borderLeftWidth'
  | 'borderLeftColor'
  | 'borderLeftStyle'
  | 'position'
  | 'boxShadow'
>;
